// This file is auto-generated by tools/generate_abi.py. DO NOT EDIT.

fn get_glyph_row(char_code: u32, row: u32) -> u32 {
    switch char_code {
        case 32u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 0u; }
                case 3u: { return 0u; }
                case 4u: { return 0u; }
                case 5u: { return 0u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 33u: {
            switch row {
                case 0u: { return 4u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 4u; }
                case 4u: { return 0u; }
                case 5u: { return 4u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 34u: {
            switch row {
                case 0u: { return 10u; }
                case 1u: { return 10u; }
                case 2u: { return 4u; }
                case 3u: { return 0u; }
                case 4u: { return 0u; }
                case 5u: { return 0u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 35u: {
            switch row {
                case 0u: { return 10u; }
                case 1u: { return 10u; }
                case 2u: { return 31u; }
                case 3u: { return 10u; }
                case 4u: { return 31u; }
                case 5u: { return 10u; }
                case 6u: { return 10u; }
                default: {{ return 0u; }}
            }
        }}
        case 36u: {
            switch row {
                case 0u: { return 4u; }
                case 1u: { return 31u; }
                case 2u: { return 5u; }
                case 3u: { return 14u; }
                case 4u: { return 20u; }
                case 5u: { return 15u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 37u: {
            switch row {
                case 0u: { return 24u; }
                case 1u: { return 25u; }
                case 2u: { return 2u; }
                case 3u: { return 4u; }
                case 4u: { return 8u; }
                case 5u: { return 19u; }
                case 6u: { return 3u; }
                default: {{ return 0u; }}
            }
        }}
        case 38u: {
            switch row {
                case 0u: { return 4u; }
                case 1u: { return 10u; }
                case 2u: { return 4u; }
                case 3u: { return 22u; }
                case 4u: { return 9u; }
                case 5u: { return 9u; }
                case 6u: { return 22u; }
                default: {{ return 0u; }}
            }
        }}
        case 39u: {
            switch row {
                case 0u: { return 2u; }
                case 1u: { return 2u; }
                case 2u: { return 4u; }
                case 3u: { return 0u; }
                case 4u: { return 0u; }
                case 5u: { return 0u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 40u: {
            switch row {
                case 0u: { return 2u; }
                case 1u: { return 4u; }
                case 2u: { return 8u; }
                case 3u: { return 8u; }
                case 4u: { return 8u; }
                case 5u: { return 4u; }
                case 6u: { return 2u; }
                default: {{ return 0u; }}
            }
        }}
        case 41u: {
            switch row {
                case 0u: { return 8u; }
                case 1u: { return 4u; }
                case 2u: { return 2u; }
                case 3u: { return 2u; }
                case 4u: { return 2u; }
                case 5u: { return 4u; }
                case 6u: { return 8u; }
                default: {{ return 0u; }}
            }
        }}
        case 42u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 4u; }
                case 2u: { return 21u; }
                case 3u: { return 14u; }
                case 4u: { return 21u; }
                case 5u: { return 4u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 43u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 31u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 44u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 0u; }
                case 3u: { return 0u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 8u; }
                default: {{ return 0u; }}
            }
        }}
        case 45u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 0u; }
                case 3u: { return 31u; }
                case 4u: { return 0u; }
                case 5u: { return 0u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 46u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 0u; }
                case 3u: { return 0u; }
                case 4u: { return 0u; }
                case 5u: { return 6u; }
                case 6u: { return 6u; }
                default: {{ return 0u; }}
            }
        }}
        case 47u: {
            switch row {
                case 0u: { return 1u; }
                case 1u: { return 2u; }
                case 2u: { return 4u; }
                case 3u: { return 8u; }
                case 4u: { return 16u; }
                case 5u: { return 0u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 48u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 19u; }
                case 3u: { return 21u; }
                case 4u: { return 25u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 49u: {
            switch row {
                case 0u: { return 4u; }
                case 1u: { return 12u; }
                case 2u: { return 4u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 50u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 1u; }
                case 3u: { return 2u; }
                case 4u: { return 4u; }
                case 5u: { return 8u; }
                case 6u: { return 31u; }
                default: {{ return 0u; }}
            }
        }}
        case 51u: {
            switch row {
                case 0u: { return 31u; }
                case 1u: { return 2u; }
                case 2u: { return 4u; }
                case 3u: { return 2u; }
                case 4u: { return 1u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 52u: {
            switch row {
                case 0u: { return 2u; }
                case 1u: { return 6u; }
                case 2u: { return 10u; }
                case 3u: { return 18u; }
                case 4u: { return 31u; }
                case 5u: { return 2u; }
                case 6u: { return 2u; }
                default: {{ return 0u; }}
            }
        }}
        case 53u: {
            switch row {
                case 0u: { return 31u; }
                case 1u: { return 16u; }
                case 2u: { return 30u; }
                case 3u: { return 1u; }
                case 4u: { return 1u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 54u: {
            switch row {
                case 0u: { return 6u; }
                case 1u: { return 8u; }
                case 2u: { return 16u; }
                case 3u: { return 30u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 55u: {
            switch row {
                case 0u: { return 31u; }
                case 1u: { return 1u; }
                case 2u: { return 2u; }
                case 3u: { return 4u; }
                case 4u: { return 8u; }
                case 5u: { return 8u; }
                case 6u: { return 8u; }
                default: {{ return 0u; }}
            }
        }}
        case 56u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 14u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 57u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 15u; }
                case 4u: { return 1u; }
                case 5u: { return 2u; }
                case 6u: { return 12u; }
                default: {{ return 0u; }}
            }
        }}
        case 58u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 6u; }
                case 2u: { return 6u; }
                case 3u: { return 0u; }
                case 4u: { return 6u; }
                case 5u: { return 6u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 59u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 6u; }
                case 2u: { return 6u; }
                case 3u: { return 0u; }
                case 4u: { return 6u; }
                case 5u: { return 6u; }
                case 6u: { return 12u; }
                default: {{ return 0u; }}
            }
        }}
        case 60u: {
            switch row {
                case 0u: { return 2u; }
                case 1u: { return 4u; }
                case 2u: { return 8u; }
                case 3u: { return 16u; }
                case 4u: { return 8u; }
                case 5u: { return 4u; }
                case 6u: { return 2u; }
                default: {{ return 0u; }}
            }
        }}
        case 61u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 31u; }
                case 3u: { return 0u; }
                case 4u: { return 31u; }
                case 5u: { return 0u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 62u: {
            switch row {
                case 0u: { return 8u; }
                case 1u: { return 4u; }
                case 2u: { return 2u; }
                case 3u: { return 1u; }
                case 4u: { return 2u; }
                case 5u: { return 4u; }
                case 6u: { return 8u; }
                default: {{ return 0u; }}
            }
        }}
        case 63u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 1u; }
                case 3u: { return 2u; }
                case 4u: { return 4u; }
                case 5u: { return 0u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 64u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 23u; }
                case 3u: { return 21u; }
                case 4u: { return 23u; }
                case 5u: { return 16u; }
                case 6u: { return 15u; }
                default: {{ return 0u; }}
            }
        }}
        case 65u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 31u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 66u: {
            switch row {
                case 0u: { return 30u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 30u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 30u; }
                default: {{ return 0u; }}
            }
        }}
        case 67u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 16u; }
                case 3u: { return 16u; }
                case 4u: { return 16u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 68u: {
            switch row {
                case 0u: { return 28u; }
                case 1u: { return 18u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 17u; }
                case 5u: { return 18u; }
                case 6u: { return 28u; }
                default: {{ return 0u; }}
            }
        }}
        case 69u: {
            switch row {
                case 0u: { return 31u; }
                case 1u: { return 16u; }
                case 2u: { return 16u; }
                case 3u: { return 30u; }
                case 4u: { return 16u; }
                case 5u: { return 16u; }
                case 6u: { return 31u; }
                default: {{ return 0u; }}
            }
        }}
        case 70u: {
            switch row {
                case 0u: { return 31u; }
                case 1u: { return 16u; }
                case 2u: { return 16u; }
                case 3u: { return 30u; }
                case 4u: { return 16u; }
                case 5u: { return 16u; }
                case 6u: { return 16u; }
                default: {{ return 0u; }}
            }
        }}
        case 71u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 16u; }
                case 3u: { return 23u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 72u: {
            switch row {
                case 0u: { return 17u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 31u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 73u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 74u: {
            switch row {
                case 0u: { return 1u; }
                case 1u: { return 1u; }
                case 2u: { return 1u; }
                case 3u: { return 1u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 75u: {
            switch row {
                case 0u: { return 17u; }
                case 1u: { return 18u; }
                case 2u: { return 20u; }
                case 3u: { return 24u; }
                case 4u: { return 20u; }
                case 5u: { return 18u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 76u: {
            switch row {
                case 0u: { return 16u; }
                case 1u: { return 16u; }
                case 2u: { return 16u; }
                case 3u: { return 16u; }
                case 4u: { return 16u; }
                case 5u: { return 16u; }
                case 6u: { return 31u; }
                default: {{ return 0u; }}
            }
        }}
        case 77u: {
            switch row {
                case 0u: { return 17u; }
                case 1u: { return 27u; }
                case 2u: { return 21u; }
                case 3u: { return 21u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 78u: {
            switch row {
                case 0u: { return 17u; }
                case 1u: { return 25u; }
                case 2u: { return 21u; }
                case 3u: { return 19u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 79u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 80u: {
            switch row {
                case 0u: { return 30u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 30u; }
                case 4u: { return 16u; }
                case 5u: { return 16u; }
                case 6u: { return 16u; }
                default: {{ return 0u; }}
            }
        }}
        case 81u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 21u; }
                case 5u: { return 18u; }
                case 6u: { return 13u; }
                default: {{ return 0u; }}
            }
        }}
        case 82u: {
            switch row {
                case 0u: { return 30u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 30u; }
                case 4u: { return 20u; }
                case 5u: { return 18u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 83u: {
            switch row {
                case 0u: { return 14u; }
                case 1u: { return 17u; }
                case 2u: { return 16u; }
                case 3u: { return 14u; }
                case 4u: { return 1u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 84u: {
            switch row {
                case 0u: { return 31u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 85u: {
            switch row {
                case 0u: { return 17u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 86u: {
            switch row {
                case 0u: { return 17u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 10u; }
                case 5u: { return 10u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 87u: {
            switch row {
                case 0u: { return 17u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 21u; }
                case 4u: { return 21u; }
                case 5u: { return 27u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 88u: {
            switch row {
                case 0u: { return 17u; }
                case 1u: { return 17u; }
                case 2u: { return 10u; }
                case 3u: { return 4u; }
                case 4u: { return 10u; }
                case 5u: { return 17u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 89u: {
            switch row {
                case 0u: { return 17u; }
                case 1u: { return 17u; }
                case 2u: { return 10u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 90u: {
            switch row {
                case 0u: { return 31u; }
                case 1u: { return 1u; }
                case 2u: { return 2u; }
                case 3u: { return 4u; }
                case 4u: { return 8u; }
                case 5u: { return 16u; }
                case 6u: { return 31u; }
                default: {{ return 0u; }}
            }
        }}
        case 91u: {
            switch row {
                case 0u: { return 6u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 6u; }
                default: {{ return 0u; }}
            }
        }}
        case 92u: {
            switch row {
                case 0u: { return 16u; }
                case 1u: { return 8u; }
                case 2u: { return 4u; }
                case 3u: { return 2u; }
                case 4u: { return 1u; }
                case 5u: { return 0u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 93u: {
            switch row {
                case 0u: { return 12u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 12u; }
                default: {{ return 0u; }}
            }
        }}
        case 94u: {
            switch row {
                case 0u: { return 4u; }
                case 1u: { return 10u; }
                case 2u: { return 17u; }
                case 3u: { return 0u; }
                case 4u: { return 0u; }
                case 5u: { return 0u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        case 95u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 0u; }
                case 3u: { return 0u; }
                case 4u: { return 0u; }
                case 5u: { return 0u; }
                case 6u: { return 31u; }
                default: {{ return 0u; }}
            }
        }}
        case 97u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 14u; }
                case 3u: { return 1u; }
                case 4u: { return 15u; }
                case 5u: { return 17u; }
                case 6u: { return 15u; }
                default: {{ return 0u; }}
            }
        }}
        case 98u: {
            switch row {
                case 0u: { return 16u; }
                case 1u: { return 16u; }
                case 2u: { return 30u; }
                case 3u: { return 17u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 30u; }
                default: {{ return 0u; }}
            }
        }}
        case 99u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 14u; }
                case 3u: { return 16u; }
                case 4u: { return 16u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 100u: {
            switch row {
                case 0u: { return 1u; }
                case 1u: { return 1u; }
                case 2u: { return 15u; }
                case 3u: { return 17u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 15u; }
                default: {{ return 0u; }}
            }
        }}
        case 101u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 14u; }
                case 3u: { return 17u; }
                case 4u: { return 31u; }
                case 5u: { return 16u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 102u: {
            switch row {
                case 0u: { return 2u; }
                case 1u: { return 4u; }
                case 2u: { return 14u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 103u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 15u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 15u; }
                case 5u: { return 1u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 104u: {
            switch row {
                case 0u: { return 16u; }
                case 1u: { return 16u; }
                case 2u: { return 30u; }
                case 3u: { return 17u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 105u: {
            switch row {
                case 0u: { return 4u; }
                case 1u: { return 0u; }
                case 2u: { return 4u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 106u: {
            switch row {
                case 0u: { return 2u; }
                case 1u: { return 0u; }
                case 2u: { return 2u; }
                case 3u: { return 2u; }
                case 4u: { return 2u; }
                case 5u: { return 18u; }
                case 6u: { return 12u; }
                default: {{ return 0u; }}
            }
        }}
        case 107u: {
            switch row {
                case 0u: { return 16u; }
                case 1u: { return 16u; }
                case 2u: { return 18u; }
                case 3u: { return 20u; }
                case 4u: { return 24u; }
                case 5u: { return 20u; }
                case 6u: { return 18u; }
                default: {{ return 0u; }}
            }
        }}
        case 108u: {
            switch row {
                case 0u: { return 4u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 109u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 26u; }
                case 3u: { return 21u; }
                case 4u: { return 21u; }
                case 5u: { return 21u; }
                case 6u: { return 21u; }
                default: {{ return 0u; }}
            }
        }}
        case 110u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 26u; }
                case 3u: { return 21u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 111u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 14u; }
                case 3u: { return 17u; }
                case 4u: { return 17u; }
                case 5u: { return 17u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 112u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 30u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 30u; }
                case 5u: { return 16u; }
                case 6u: { return 16u; }
                default: {{ return 0u; }}
            }
        }}
        case 113u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 15u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 15u; }
                case 5u: { return 1u; }
                case 6u: { return 1u; }
                default: {{ return 0u; }}
            }
        }}
        case 114u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 26u; }
                case 3u: { return 21u; }
                case 4u: { return 16u; }
                case 5u: { return 16u; }
                case 6u: { return 16u; }
                default: {{ return 0u; }}
            }
        }}
        case 115u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 15u; }
                case 3u: { return 16u; }
                case 4u: { return 14u; }
                case 5u: { return 1u; }
                case 6u: { return 30u; }
                default: {{ return 0u; }}
            }
        }}
        case 116u: {
            switch row {
                case 0u: { return 4u; }
                case 1u: { return 4u; }
                case 2u: { return 31u; }
                case 3u: { return 4u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 2u; }
                default: {{ return 0u; }}
            }
        }}
        case 117u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 17u; }
                case 5u: { return 19u; }
                case 6u: { return 13u; }
                default: {{ return 0u; }}
            }
        }}
        case 118u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 17u; }
                case 5u: { return 10u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 119u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 17u; }
                case 3u: { return 21u; }
                case 4u: { return 21u; }
                case 5u: { return 21u; }
                case 6u: { return 10u; }
                default: {{ return 0u; }}
            }
        }}
        case 120u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 17u; }
                case 3u: { return 10u; }
                case 4u: { return 4u; }
                case 5u: { return 10u; }
                case 6u: { return 17u; }
                default: {{ return 0u; }}
            }
        }}
        case 121u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 17u; }
                case 2u: { return 17u; }
                case 3u: { return 17u; }
                case 4u: { return 15u; }
                case 5u: { return 1u; }
                case 6u: { return 14u; }
                default: {{ return 0u; }}
            }
        }}
        case 122u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 31u; }
                case 3u: { return 2u; }
                case 4u: { return 4u; }
                case 5u: { return 8u; }
                case 6u: { return 31u; }
                default: {{ return 0u; }}
            }
        }}
        case 123u: {
            switch row {
                case 0u: { return 2u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 8u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 2u; }
                default: {{ return 0u; }}
            }
        }}
        case 124u: {
            switch row {
                case 0u: { return 4u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 0u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 4u; }
                default: {{ return 0u; }}
            }
        }}
        case 125u: {
            switch row {
                case 0u: { return 8u; }
                case 1u: { return 4u; }
                case 2u: { return 4u; }
                case 3u: { return 2u; }
                case 4u: { return 4u; }
                case 5u: { return 4u; }
                case 6u: { return 8u; }
                default: {{ return 0u; }}
            }
        }}
        case 126u: {
            switch row {
                case 0u: { return 0u; }
                case 1u: { return 0u; }
                case 2u: { return 8u; }
                case 3u: { return 21u; }
                case 4u: { return 2u; }
                case 5u: { return 0u; }
                case 6u: { return 0u; }
                default: {{ return 0u; }}
            }
        }}
        default: {{ return 0u; }}
    }
}
