// This file is auto-generated by tools/generate_abi.py. DO NOT EDIT.

struct GlyphData {
    rows: array<u32, 7>,
}

@group(0) @binding(2) var<storage, read> glyph_atlas: array<GlyphData>;

fn get_glyph_row(char_code: u32, row: u32) -> u32 {
    if (char_code >= 32u && char_code <= 126u) {
        let index = char_code - 32u;
        return glyph_atlas[index].rows[row];
    } else {
        return 0u;
    }
}
