import re

def parse_glyph_atlas(abi_content):
    """Parses the glyph atlas from the pixel_abi.md content."""
    glyph_atlas = {}
    # Regex to find character and its hex data
    pattern = re.compile(r"\*\s+`(.+?)`\s*:\s*`(.+?)`")
    matches = pattern.findall(abi_content)

    for char, data in matches:
        # Handle the space character specifically
        if char == "(space)":
            char = " "

        # Convert hex strings to integers
        glyph_atlas[char] = [int(h, 16) for h in data.split(', ')]

    return glyph_atlas

def generate_python_abi(glyph_atlas):
    """Generates the content for pxl_os/pixel_abi.py."""
    py_content = "# This file is auto-generated by tools/generate_abi.py. DO NOT EDIT.\n\n"
    py_content += "GLYPH_ATLAS = {\n"
    for char, data in glyph_atlas.items():
        # Escape special characters for Python string
        char_repr = repr(char)
        py_content += f"    {char_repr}: {data},\n"
    py_content += "}\n"
    return py_content

def generate_wgsl_abi(glyph_atlas):
    """Generates the content for shaders/pixel_abi.wgsl."""
    wgsl_content = "// This file is auto-generated by tools/generate_abi.py. DO NOT EDIT.\n\n"
    wgsl_content += "struct GlyphData {\n"
    wgsl_content += "    rows: array<u32, 7>,\n"
    wgsl_content += "}\n\n"
    wgsl_content += "@group(0) @binding(2) var<storage, read> glyph_atlas: array<GlyphData>;\n\n"
    wgsl_content += "fn get_glyph_row(char_code: u32, row: u32) -> u32 {\n"
    wgsl_content += "    if (char_code >= 32u && char_code <= 126u) {\n"
    wgsl_content += "        let index = char_code - 32u;\n"
    wgsl_content += "        return glyph_atlas[index].rows[row];\n"
    wgsl_content += "    } else {\n"
    wgsl_content += "        return 0u;\n"
    wgsl_content += "    }\n"
    wgsl_content += "}\n"
    return wgsl_content

def main():
    """Main function to generate ABI files."""
    try:
        with open("pixel_abi.md", "r") as f:
            abi_content = f.read()
    except FileNotFoundError:
        print("Error: pixel_abi.md not found.")
        return

    glyph_atlas = parse_glyph_atlas(abi_content)

    # Generate and write Python ABI file
    py_abi_content = generate_python_abi(glyph_atlas)
    with open("pxl_os/pixel_abi.py", "w") as f:
        f.write(py_abi_content)
    print("Generated pxl_os/pixel_abi.py")

    # Generate and write WGSL ABI file
    wgsl_abi_content = generate_wgsl_abi(glyph_atlas)
    with open("shaders/pixel_abi.wgsl", "w") as f:
        f.write(wgsl_abi_content)
    print("Generated shaders/pixel_abi.wgsl")

if __name__ == "__main__":
    main()
